config/routes.rb
BasicApp::Application.routes.draw do

  root :to => "home#index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
         # :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3= 'Hello ' + current_user.email if current_user

app/views/layouts/_flashes.html.haml
- flash.each do |key, value|
  %div{:class=>"alert-message #{key}"}
    %a{:class => 'close', :href => '#'} x
    %p= html_escape(value)

app/views/layouts/_user_menu.html.haml
.row
  .span6.columns.offset10
    .right
      - if current_user
        = current_user.email
        |
        = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
        |
        = link_to 'Edit account', edit_user_registration_path
        - if current_user.admin?
          |
          = link_to 'Admin', rails_admin_path
      - else
        = link_to 'Sign in', user_session_path
        or
        = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{ :content => 'text/html; charset=utf-8', 'http-equiv' => 'Content-Type' }
    %meta{ :name => 'keywords', :content => '' }
    %meta{ :name => 'description', :content => '' }

    %title Basic App
    = stylesheet_link_tag    :application
    = javascript_include_tag :application
    = csrf_meta_tag

    / %link{:href=>'/images/logo.png', :rel=>'apple-touch-icon'}
    / %link{:href=>'/favicon.ico', :rel=>'shortcut icon'}

  %body
    .container
      = render :partial => 'layouts/user_menu'

      .page-header
        %h1=link_to 'Basic App', root_path

      .content
        = render :partial => 'layouts/flashes'
        = yield

      .footer
        %a{ :href => '/' }
          Basic application with devise and bootstrap